### ISSUE TITLE
Update example to use ref instead of state for keycloak existence check

### ISSUE THREAD

**Issue by ttante** [marmelab/ra-keycloak#8]
The example provided causes an infinite redirect loop, similar to the [the one described here](https://stackoverflow.com/questions/72457689/keycloak-causes-loops-in-react-application-after-i-have-just-login-on-keycloak-a) and in many other instances with keycloak and the keycloak-js module.

In the example provided the [keycloak existence check on this line](https://github.com/marmelab/ra-keycloak/blob/1521348eeef0398f06d5141289001c68e9f4cc41/packages/demo/src/App.tsx#L66) causes an extra render in the app, which causes keycloak to redirect infinitely.

I resolved this by creating a new ref called 'didInit' (default value of false), which i set to true alongside keycloak init. Checking for the existence of this ref instead of the 'keycloak' state-stored variable resolves the extra render, which allows keycloak to work smoothly.

If there is a preferred workaround please let me know, otherwise I advise updating the example to use a ref as I described.

**Comment by fzaninotto** [comment]
Nice! Would you like to open a PR to fix the documentation?

**Comment by ttante** [comment]
@fzaninotto I made the changes in a branch but I don't have access to push. Not sure if it's an access thing or I just don't have my credentials correct. I don't normally have issues pushing.

**Comment by fzaninotto** [comment]
You have to fork the repository first.

**Comment by MattMx** [comment]
@ttante Could you please provide a snippet containing your changes? Sadly I also encountered the infinite loop problem

**Comment by MattMx** [comment]
I believe I resolved the issue thanks to an awaiting pull request:
https://github.com/marmelab/ra-keycloak/pull/5

**Comment by djhi** [comment]
Not needed anymore with v2
